# Generated by Django 4.0.1 on 2022-01-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_candidate_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resume'),
        ),
    ]
